/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package info.ditrapani

class Main {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(Main().greeting)
}
